sudo: required
dist: bionic
language: python
matrix:
  include:
    - language: python
      python: 3.7
      cache: pip
      install:
        - pip install -r requirements.txt
      services:
        - postgresql
      addons:
        postgresql: '10'
      before_script:
        - psql -U postgres -f setup_db_postgresql.sql
        - python3 manage.py migrate
      script:
        - python3 manage.py test
