sudo: required
dist: bionic
language: python
python: 3.7
cache: pip
install:
- pip install -r requirements.txt
services:
- postgresql
addons:
  postgresql: '10'
before_script:
- psql -U postgres -f dev_setup_postgresql.sql
- python3 manage.py migrate
script:
- coverage run manage.py test
after_success:
- codecov
